name = "lightson"
main = "src/index.js"
compatibility_date = "2026-09-12"
workers_dev = true
account_id = "db80b407c9444b69c5bc38bbe07efb38"

[triggers]
crons = ["*/5 * * * *"]

[[routes]]
pattern = "lightson.shadowstar.io"
custom_domain = true

[[routes]]
pattern = "lightson.xoza.net"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "lightson"
database_id = "d171d9e5-0dd2-47c8-a41d-43b4a221f449"
